---
title: danielbernal.co
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    baseurl: /blog
    paginate_path: /blog/page:num/
name: Daniel Bernal
description: I WRITE IOS APPS WHILE TINKERING ON THE INTERWEBS FROM BEAUTIFUL VALENCIA.
url: https://danielbernal.co
permalink: "/:year/:month/:day/:title/"
paginate: 10
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: compressed
plugins:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
exclude:
- LICENSE
- README.md
- CNAME
excerpt_separator: "<!--more-->"
future: false
highlighter: rouge
