---
title: Danielbernal.Co
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Daniel Bernal
description: I'm Daniel Bernal and I write apps while tinkering on the interweb from
  Spain.
paginate: 100
url: https://danielbernal.co
baseurl: 
permalink: "/:year/:month/:day/:title/"
paginate_path: "/page:num/"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
exclude:
- LICENSE
- README.md
- CNAME
excerpt_separator: "<!--more-->"
future: false
highlighter: rouge
